//! Proof skeleton generation for Coq and Lean 4.
//!
//! At `--strict=4 --emit-proof`, Crust emits a `.v` (Coq) and a `.lean`
//! (Lean 4) file alongside the generated `.rs` file.  Each file contains:
//!
//! - Type definitions translated to inductive types.
//! - Function signatures translated to theorem statements.
//! - `#[requires]`/`#[ensures]` annotations as pre/postconditions.
//! - Proof obligations (VCs) with `admit`/`sorry` placeholders for a
//!   human verifier or an automated tactic to fill in.
//!
//! The generated files are syntactically valid but logically incomplete;
//! the `sorry`/`admit` placeholders deliberately prevent the provers from
//! accepting the file without real proofs.

use crate::ast::*;
use crate::contracts::VerifCondition;

// ── Coq emitter ───────────────────────────────────────────────────────────────

pub struct CoqEmitter;

impl CoqEmitter {
    pub fn emit_program(items: &[Item], vcs: &[VerifCondition]) -> String {
        let mut out = String::new();
        out.push_str("(* Generated by Crust --emit-proof  *)\n");
        out.push_str("(* Fill in the `admit` placeholders with real proofs. *)\n\n");
        out.push_str("Require Import ZArith.\nOpen Scope Z_scope.\n\n");

        for item in items {
            match item {
                Item::Struct(s) => {
                    out.push_str(&emit_coq_struct(s));
                    out.push('\n');
                }
                Item::Enum(e) => {
                    out.push_str(&emit_coq_enum(e));
                    out.push('\n');
                }
                Item::Fn(f) => {
                    out.push_str(&emit_coq_fn_spec(f, vcs));
                    out.push('\n');
                }
                Item::Impl(imp) => {
                    for method in &imp.methods {
                        out.push_str(&emit_coq_fn_spec(method, vcs));
                        out.push('\n');
                    }
                }
                _ => {}
            }
        }
        out
    }
}

fn emit_coq_struct(s: &StructDef) -> String {
    let mut out = format!("Record {} := {{\n", s.name);
    for (name, ty) in &s.fields {
        out.push_str(&format!("  {} : {};\n", name, coq_ty(ty)));
    }
    out.push_str("}.\n");
    out
}

fn emit_coq_enum(e: &EnumDef) -> String {
    let mut out = format!("Inductive {} :=\n", e.name);
    for v in &e.variants {
        match &v.data {
            VariantData::Unit => out.push_str(&format!("  | {}\n", v.name)),
            VariantData::Tuple(tys) => {
                let args = tys.iter().map(coq_ty).collect::<Vec<_>>().join(" * ");
                if tys.len() > 1 {
                    out.push_str(&format!("  | {} : ({}) -> {}\n", v.name, args, e.name));
                } else {
                    out.push_str(&format!("  | {} : {} -> {}\n", v.name, args, e.name));
                }
            }
            VariantData::Struct(fields) => {
                let args = fields.iter()
                    .map(|(_, t)| coq_ty(t))
                    .collect::<Vec<_>>()
                    .join(" -> ");
                out.push_str(&format!("  | {} : {} -> {}\n", v.name, args, e.name));
            }
        }
    }
    out.push_str(".\n");
    out
}

fn emit_coq_fn_spec(f: &FnDef, all_vcs: &[VerifCondition]) -> String {
    let mut out = String::new();

    let params_str = f.params.iter()
        .filter(|p| !p.is_self)
        .map(|p| format!("({} : {})", p.name, coq_ty(&p.ty)))
        .collect::<Vec<_>>()
        .join(" ");

    let ret_str = f.ret_ty.as_ref().map(|t| coq_ty(t)).unwrap_or_else(|| "unit".into());

    // Extract requires / ensures for this function
    let requires: Vec<String> = f.attrs.iter().filter_map(|a| {
        if let Attr::Requires(e) = a { Some(pretty_coq_expr(e)) } else { None }
    }).collect();
    let ensures: Vec<String> = f.attrs.iter().filter_map(|a| {
        if let Attr::Ensures(e) = a { Some(pretty_coq_expr(e)) } else { None }
    }).collect();

    let fn_vcs: Vec<&VerifCondition> =
        all_vcs.iter().filter(|v| v.fn_name == f.name).collect();

    if requires.is_empty() && ensures.is_empty() && fn_vcs.is_empty() {
        // No contracts → emit a simple axiom placeholder
        out.push_str(&format!(
            "(* Specification for {} *)\n\
             Axiom {}_spec : forall{}, {}.\n",
            f.name, f.name,
            if params_str.is_empty() { String::new() } else { format!(" {}", params_str) },
            ret_str,
        ));
        return out;
    }

    // Build precondition
    let pre = if requires.is_empty() {
        "True".into()
    } else {
        requires.join(" /\\ ")
    };

    // Build postcondition (using `result` for the return value)
    let post = if ensures.is_empty() {
        "True".into()
    } else {
        ensures.join(" /\\ ")
    };

    out.push_str(&format!(
        "(* Contract theorem for {} *)\n\
         Theorem {}_contract{} :\n  {} ->\n  let result := (* body *) tt in\n  {}.\n\
         Proof.\n  admit. (* TODO: fill in proof *)\nQed.\n",
        f.name, f.name,
        if params_str.is_empty() { String::new() } else { format!(" {}", params_str) },
        pre,
        post,
    ));

    // Additional VCs
    for (i, vc) in fn_vcs.iter().enumerate() {
        out.push_str(&format!(
            "(* VC #{}: [{}] {} *)\n\
             Lemma {}_{}_vc_{}{} : {}.\nProof. admit. Qed.\n",
            i + 1, vc.kind_str(), vc.expr,
            f.name, vc.kind_str(), i + 1,
            if params_str.is_empty() { String::new() } else { format!(" {}", params_str) },
            vc.expr,
        ));
    }

    out
}

fn coq_ty(ty: &Ty) -> String {
    match ty {
        Ty::Named(s) => match s.as_str() {
            "i8" | "i16" | "i32" | "i64" | "i128" | "isize" |
            "u8" | "u16" | "u32" | "u64" | "u128" | "usize" => "Z".into(),
            "f32" | "f64" => "R".into(),
            "bool"   => "bool".into(),
            "String" | "str" => "string".into(),
            other    => other.to_string(),
        },
        Ty::Unit | Ty::Never => "unit".into(),
        Ty::Ref(_, inner) | Ty::Ptr(_, inner) => coq_ty(inner),
        Ty::Slice(inner)  => format!("list {}", coq_ty(inner)),
        Ty::Tuple(tys) => {
            if tys.is_empty() { "unit".into() }
            else { format!("({})", tys.iter().map(coq_ty).collect::<Vec<_>>().join(" * ")) }
        }
        Ty::Generic(name, args) => {
            let args_str = args.iter().map(coq_ty).collect::<Vec<_>>().join(" ");
            if args_str.is_empty() { name.clone() } else { format!("({} {})", name, args_str) }
        }
        Ty::Lifetime(_) => "unit".into(), // lifetimes have no Coq representation
    }
}

fn pretty_coq_expr(expr: &Expr) -> String {
    match expr {
        Expr::Lit(Lit::Int(n))  => n.to_string(),
        Expr::Lit(Lit::Bool(b)) => b.to_string(),
        Expr::Ident(name)       => name.clone(),
        Expr::Binary(op, l, r) => {
            let op_str = match op {
                BinOp::Add => "+", BinOp::Sub => "-", BinOp::Mul => "*",
                BinOp::Div => "/", BinOp::Rem => "mod",
                BinOp::Eq  => "=",  BinOp::Ne  => "<>",
                BinOp::Lt  => "<",  BinOp::Le  => "<=",
                BinOp::Gt  => ">",  BinOp::Ge  => ">=",
                BinOp::And => "/\\", BinOp::Or  => "\\/",
                _ => "?",
            };
            format!("({} {} {})", pretty_coq_expr(l), op_str, pretty_coq_expr(r))
        }
        Expr::Unary(UnOp::Neg, e) => format!("(-{})", pretty_coq_expr(e)),
        Expr::Unary(UnOp::Not, e) => format!("(~ {})", pretty_coq_expr(e)),
        _ => format!("(*unsupported*) True"),
    }
}

// ── Lean 4 emitter ────────────────────────────────────────────────────────────

pub struct LeanEmitter;

impl LeanEmitter {
    pub fn emit_program(items: &[Item], vcs: &[VerifCondition]) -> String {
        let mut out = String::new();
        out.push_str("-- Generated by Crust --emit-proof\n");
        out.push_str("-- Fill in the `sorry` placeholders with real proofs.\n\n");
        out.push_str("import Mathlib.Data.Int.Basic\n\n");

        for item in items {
            match item {
                Item::Struct(s) => {
                    out.push_str(&emit_lean_struct(s));
                    out.push('\n');
                }
                Item::Enum(e) => {
                    out.push_str(&emit_lean_enum(e));
                    out.push('\n');
                }
                Item::Fn(f) => {
                    out.push_str(&emit_lean_fn_spec(f, vcs));
                    out.push('\n');
                }
                Item::Impl(imp) => {
                    for method in &imp.methods {
                        out.push_str(&emit_lean_fn_spec(method, vcs));
                        out.push('\n');
                    }
                }
                _ => {}
            }
        }
        out
    }
}

fn emit_lean_struct(s: &StructDef) -> String {
    let mut out = format!("structure {} where\n", s.name);
    for (name, ty) in &s.fields {
        out.push_str(&format!("  {} : {}\n", name, lean_ty(ty)));
    }
    out
}

fn emit_lean_enum(e: &EnumDef) -> String {
    let mut out = format!("inductive {} where\n", e.name);
    for v in &e.variants {
        match &v.data {
            VariantData::Unit => out.push_str(&format!("  | {}\n", v.name)),
            VariantData::Tuple(tys) => {
                let args = tys.iter()
                    .enumerate()
                    .map(|(i, t)| format!("(field{} : {})", i, lean_ty(t)))
                    .collect::<Vec<_>>()
                    .join(" ");
                out.push_str(&format!("  | {} {}: {}\n", v.name, args, e.name));
            }
            VariantData::Struct(fields) => {
                let args = fields.iter()
                    .map(|(n, t)| format!("({} : {})", n, lean_ty(t)))
                    .collect::<Vec<_>>()
                    .join(" ");
                out.push_str(&format!("  | {} {}: {}\n", v.name, args, e.name));
            }
        }
    }
    out
}

fn emit_lean_fn_spec(f: &FnDef, all_vcs: &[VerifCondition]) -> String {
    let mut out = String::new();

    let params_str = f.params.iter()
        .filter(|p| !p.is_self)
        .map(|p| format!("({} : {})", p.name, lean_ty(&p.ty)))
        .collect::<Vec<_>>()
        .join(" ");

    let ret_str = f.ret_ty.as_ref().map(|t| lean_ty(t)).unwrap_or_else(|| "Unit".into());

    let requires: Vec<String> = f.attrs.iter().filter_map(|a| {
        if let Attr::Requires(e) = a { Some(pretty_lean_expr(e)) } else { None }
    }).collect();
    let ensures: Vec<String> = f.attrs.iter().filter_map(|a| {
        if let Attr::Ensures(e) = a { Some(pretty_lean_expr(e)) } else { None }
    }).collect();

    let fn_vcs: Vec<&VerifCondition> =
        all_vcs.iter().filter(|v| v.fn_name == f.name).collect();

    let pre = if requires.is_empty() { "True".into() } else { requires.join(" ∧ ") };
    let post = if ensures.is_empty() { "True".into() } else { ensures.join(" ∧ ") };

    if !requires.is_empty() || !ensures.is_empty() {
        out.push_str(&format!(
            "-- Contract theorem for {}\n\
             theorem {}_contract {}: {} → {} := by\n  sorry\n",
            f.name, f.name,
            if params_str.is_empty() { String::new() } else { format!(" {}", params_str) },
            pre, post,
        ));
    } else {
        out.push_str(&format!(
            "-- Specification for {}\n\
             opaque {}_spec {}: {} := by sorry\n",
            f.name, f.name,
            if params_str.is_empty() { String::new() } else { format!(" {}", params_str) },
            ret_str,
        ));
    }

    // Additional VCs
    for (i, vc) in fn_vcs.iter().enumerate() {
        out.push_str(&format!(
            "-- VC #{}: [{}] {}\n\
             theorem {}_{}_vc_{} {}: {} := by\n  sorry\n",
            i + 1, vc.kind_str(), vc.expr,
            f.name, vc.kind_str(), i + 1,
            if params_str.is_empty() { String::new() } else { format!(" {}", params_str) },
            vc.expr,
        ));
    }

    out
}

fn lean_ty(ty: &Ty) -> String {
    match ty {
        Ty::Named(s) => match s.as_str() {
            "i8" | "i16" | "i32" | "i64" | "i128" | "isize" => "Int".into(),
            "u8" | "u16" | "u32" | "u64" | "u128" | "usize" => "Nat".into(),
            "f32" | "f64" => "Float".into(),
            "bool"   => "Bool".into(),
            "String" | "str" | "&str" => "String".into(),
            other    => other.to_string(),
        },
        Ty::Unit | Ty::Never => "Unit".into(),
        Ty::Ref(_, inner) | Ty::Ptr(_, inner) => lean_ty(inner),
        Ty::Slice(inner)  => format!("Array {}", lean_ty(inner)),
        Ty::Tuple(tys) => {
            if tys.is_empty() { "Unit".into() }
            else { format!("({})", tys.iter().map(lean_ty).collect::<Vec<_>>().join(" × ")) }
        }
        Ty::Generic(name, args) => {
            let args_str = args.iter().map(lean_ty).collect::<Vec<_>>().join(" ");
            if args_str.is_empty() { name.clone() } else { format!("({} {})", name, args_str) }
        }
        Ty::Lifetime(_) => "Unit".into(),
    }
}

fn pretty_lean_expr(expr: &Expr) -> String {
    match expr {
        Expr::Lit(Lit::Int(n))  => n.to_string(),
        Expr::Lit(Lit::Bool(b)) => if *b { "True".into() } else { "False".into() },
        Expr::Ident(name)       => name.clone(),
        Expr::Binary(op, l, r) => {
            let op_str = match op {
                BinOp::Add => "+", BinOp::Sub => "-", BinOp::Mul => "*",
                BinOp::Div => "/", BinOp::Rem => "%",
                BinOp::Eq  => "=",  BinOp::Ne  => "≠",
                BinOp::Lt  => "<",  BinOp::Le  => "≤",
                BinOp::Gt  => ">",  BinOp::Ge  => "≥",
                BinOp::And => "∧", BinOp::Or  => "∨",
                _ => "?",
            };
            format!("({} {} {})", pretty_lean_expr(l), op_str, pretty_lean_expr(r))
        }
        Expr::Unary(UnOp::Neg, e) => format!("(-{})", pretty_lean_expr(e)),
        Expr::Unary(UnOp::Not, e) => format!("(¬ {})", pretty_lean_expr(e)),
        _ => "True".into(),
    }
}
